#!/bin/bash
# qq fav
# Usage:
#   qq fav <path> <name>
#
# Tag a given path with a name so it can be referred to later.

QQTOOLS_OUTPUT_PREFIX="fav"

mkdir -p "$QQTOOLS_HOME/favs"

path=$(readlink -f "$1")
name="$2"

if [[ -z "$path" || -z "$name" ]]; then
  output "Usage:"
  output "  qq fav [path] [name]"
  output
  output "Tag a given path with a name so it can be referred to later."
  exit 1
fi

fav="$QQTOOLS_HOME/favs/$name"
echo "$path" > "$fav"

output "Tagged $path as '$name'."

