#!/bin/bash
# qq unfav
# Usage:
#   qq unfav <name>
#
# Remove a named tag directory.

name="$1"
if [ -z "$name" ]; then
  output "Usage:"
  output "  qq unfav [name]"
  output
  output "Remove a named tag directory."
fi
